import createFeedRoutes from './routes/feed.js';
import { createFeedQueries } from './db/feed.js';
import createChallengeCreationRoutes from './routes/challengeCreations.js';
import createChallengeActionsRoutes from './routes/challengeActions.js';
import createChallengesRoutes from './routes/challenges.js';
import { createChallengeQueries } from './db/challenges.js';
import createAdminProfileRoutes from './routes/adminProfile.js';
import {apiKeyBearerMiddleware,integrationBearerMiddleware} from './routes/middleware/bearer.js';
import createHelpRoutes from './routes/help.js';
import createTryRoutes from './routes/try.js';
import {randomUUID} from 'node:crypto';
import createProfileRoutes from './routes/profile.js';
import createProfileBrowseRoutes from './routes/profileBrowse.js';
import createFollowsRoutes from './routes/follows.js';
import createPresenceRoutes from './routes/presence.js';
import createIntegrationRoutes from './routes/integrations.js';
import createGooglePhotosRoutes from './routes/googlePhotos.js';
import createLibraryRoutes from './routes/library.js';
import createAudioClipsRoutes from './routes/audioClips.js';
import { createExploreRoutes } from './routes/explore.js';
import { createCommentsRoutes } from './routes/comments.js';
import createSuggestRoutes from './routes/suggestions.js';
import "dotenv/config";
import cookieParser from "cookie-parser";
import express from "express";
import path from "node:path";
import { fileURLToPath } from "node:url";
import WebSocket from "ws";
import { createFaviconRoutes } from "./routes/favicon.js";
import { createAuthRoutes } from "./routes/auth.js";
import { createCdnRoutes } from "./routes/cdn.js";
import { createGenericRoutes } from "./routes/generic.js";
import { createFilesCors } from "./routes/middleware/filesCors.js";
import { createAuthMiddleware } from "./routes/middleware/auth.js";
import { createCdnHostBoundary } from "./routes/middleware/cdnHost.js";
import createPageRoutes from "./routes/pages.js";
import { createDb } from "./db/index.js";
import { createAppDataRoutes } from "./routes/appData.js";
import { createCreationsRoutes } from "./routes/creations.js";
import { createThreadsRoutes } from './routes/threads.js';
import { createRealtimeAuthRoutes } from './routes/realtimeAuth.js';
import createYoutubeRoutes from './routes/youtube.js';
import createSunoRoutes from './routes/suno.js';
import createXRoutes from './routes/x.js';
import createCreateRoutes from './routes/create.js';
import { resumeLocalProviderPolls } from './services/create/creationJob.js';

// Supabase Realtime needs a WebSocket implementation on Node 20.
if (!globalThis.WebSocket) globalThis.WebSocket = WebSocket;

const port = Number(process.env.PORT || 3000);
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const bindHost = process.env.NODE_ENV === "production" ? "0.0.0.0" : "127.0.0.1";
const pagesDir = path.join(__dirname, "pages");
const app = express();
const db = createDb();

app.set("trust proxy", true);
app.use("/api/auth", express.json({ limit: "1mb" }));
app.use("/api", express.json({ limit: "1mb" }));
app.use("/api/notifications", express.urlencoded({ extended: false }));
app.use('/oauth',express.urlencoded({extended:false}));
app.use(cookieParser());
app.use(createFaviconRoutes({ publicDir: path.join(__dirname, "public") }));
app.use(createAuthMiddleware(db.sessions, db.users));
app.use(apiKeyBearerMiddleware(db.account.queries));app.use(integrationBearerMiddleware());
// The beta application also serves the public profile/edited-image compatibility
// path. The CDN host serves the same VPS-owned route through createCdnRoutes.
app.use("/api/images/generic", createFilesCors(), createGenericRoutes(db.genericFiles, db.users));
app.use(createCdnHostBoundary(createCdnRoutes({ profileFiles: db.profileFiles, genericFiles: db.genericFiles, users: db.users })));
const challengeDependencies = { ...db.account, queries: { ...db.account.queries, ...createChallengeQueries(db.account.client) } };
app.use(createChallengeActionsRoutes(challengeDependencies));
app.use(createChallengesRoutes(challengeDependencies));
app.use(createFeedRoutes({ queries: { ...db.account.queries, ...createFeedQueries(db.account.client) } }));
const challengeCreations = createChallengeCreationRoutes(challengeDependencies);
app.use(challengeCreations);
app.use(createThreadsRoutes({ threads: db.threads }));
app.use(createRealtimeAuthRoutes({ realtimeAuth: db.realtimeAuth }));
app.use(createYoutubeRoutes());
app.use(createSunoRoutes());
app.use(createXRoutes());
app.post('/api/policy/seen',(req,res)=>{if(!req.cookies?.ps_cid)res.cookie('ps_cid',randomUUID(),{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:365*86400000,path:'/'});res.json({ok:true})});
app.use(createTryRoutes(db.account));
app.use(createHelpRoutes({pagesDir}));
app.use(createAdminProfileRoutes(db.account));
app.use(createProfileRoutes(db.account));
app.use(createProfileBrowseRoutes(db.account));
app.use(createFollowsRoutes(db.account));
app.use(createPresenceRoutes(db.account));
app.use(createIntegrationRoutes(db.account));
app.use(createGooglePhotosRoutes(db.account));
app.use(createAppDataRoutes({ users: db.users, credits: db.credits, notifications: db.notifications, servers: db.servers }));
app.use(createCreateRoutes(db.create));
app.use(createLibraryRoutes(db.library));
app.use(createAudioClipsRoutes(db.library));
app.use(createSuggestRoutes({ queries: db.suggestions }));
app.use(createExploreRoutes({ explore: db.explore, users: db.users }));
app.use(createCommentsRoutes({ comments: db.comments, users: db.users }));
app.use(createCreationsRoutes({ creations: db.creations, users: db.users, appendChallengeEligibility: challengeCreations.appendEligibility }));
app.use(createAuthRoutes({ users: db.users, sessions: db.sessions }));
app.use(createPageRoutes({ pagesDir, users: db.users }));
app.use(express.static(path.join(__dirname, "public")));
app.use((error, req, res, next) => {
	console.error("[beta] request failed", error);
	if (res.headersSent) return next(error);
	res.status(500).json({ error: "Internal server error" });
});

app.listen(port, bindHost, () => {
	console.log(`Parascene beta dev server: http://localhost:${port}/`);
	console.log(`[beta] bound to ${bindHost}:${port}`);
 void resumeLocalProviderPolls(db.create).catch(error => console.error("[beta] Create poll recovery failed", error));
});
