-- Chat: DM + hashtag channels (run after supabase_01/02; requires prsn_users).

CREATE TABLE IF NOT EXISTS prsn_chat_threads (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	type text NOT NULL CHECK (type IN ('dm', 'channel')),
	dm_pair_key text,
	channel_slug text,
	created_at timestamptz NOT NULL DEFAULT now(),
	CHECK (
		(type = 'dm' AND dm_pair_key IS NOT NULL AND channel_slug IS NULL)
		OR (type = 'channel' AND channel_slug IS NOT NULL AND dm_pair_key IS NULL)
	)
);

CREATE UNIQUE INDEX IF NOT EXISTS prsn_chat_threads_dm_pair_key_unique
	ON prsn_chat_threads (dm_pair_key)
	WHERE type = 'dm';

CREATE UNIQUE INDEX IF NOT EXISTS prsn_chat_threads_channel_slug_unique
	ON prsn_chat_threads (channel_slug)
	WHERE type = 'channel';

CREATE TABLE IF NOT EXISTS prsn_chat_members (
	thread_id bigint NOT NULL REFERENCES prsn_chat_threads(id) ON DELETE CASCADE,
	user_id bigint NOT NULL REFERENCES prsn_users(id) ON DELETE CASCADE,
	joined_at timestamptz NOT NULL DEFAULT now(),
	PRIMARY KEY (thread_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_prsn_chat_members_user_id
	ON prsn_chat_members(user_id);

CREATE TABLE IF NOT EXISTS prsn_chat_messages (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	thread_id bigint NOT NULL REFERENCES prsn_chat_threads(id) ON DELETE CASCADE,
	sender_id bigint NOT NULL REFERENCES prsn_users(id) ON DELETE CASCADE,
	body text NOT NULL,
	created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_prsn_chat_messages_thread_created
	ON prsn_chat_messages(thread_id, created_at DESC, id DESC);

ALTER TABLE prsn_chat_threads ENABLE ROW LEVEL SECURITY;
ALTER TABLE prsn_chat_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE prsn_chat_messages ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE prsn_chat_threads IS 'Parascene: chat threads (DM or hashtag channel). API + service role only.';
COMMENT ON TABLE prsn_chat_members IS 'Parascene: thread membership. API + service role only.';
COMMENT ON TABLE prsn_chat_messages IS 'Parascene: chat messages. API + service role only.';

-- Paginated fetch: latest rows first; optional cursor = strictly older than (p_before_created_at, p_before_id).
CREATE OR REPLACE FUNCTION prsn_chat_messages_page(
	p_thread_id bigint,
	p_before_created_at timestamptz,
	p_before_id bigint,
	p_limit int
)
RETURNS SETOF prsn_chat_messages
LANGUAGE sql
STABLE
AS $$
	SELECT m.*
	FROM prsn_chat_messages m
	WHERE m.thread_id = p_thread_id
	AND (
		(p_before_created_at IS NULL AND p_before_id IS NULL)
		OR (m.created_at, m.id) < (p_before_created_at, p_before_id)
	)
	ORDER BY m.created_at DESC, m.id DESC
	LIMIT p_limit;
$$;
