-- Chat: DM + hashtag channels + Realtime Broadcast RLS (run after supabase_01/02; requires prsn_users).

CREATE TABLE IF NOT EXISTS prsn_chat_threads (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	type text NOT NULL CHECK (type IN ('dm', 'channel')),
	dm_pair_key text,
	channel_slug text,
	created_at timestamptz NOT NULL DEFAULT now(),
	meta jsonb NOT NULL DEFAULT '{}'::jsonb,
	CHECK (
		(type = 'dm' AND dm_pair_key IS NOT NULL AND channel_slug IS NULL)
		OR (type = 'channel' AND channel_slug IS NOT NULL AND dm_pair_key IS NULL)
	)
);

CREATE UNIQUE INDEX IF NOT EXISTS prsn_chat_threads_dm_pair_key_unique
	ON prsn_chat_threads (dm_pair_key)
	WHERE type = 'dm';

CREATE UNIQUE INDEX IF NOT EXISTS prsn_chat_threads_channel_slug_unique
	ON prsn_chat_threads (channel_slug)
	WHERE type = 'channel';

CREATE TABLE IF NOT EXISTS prsn_chat_members (
	thread_id bigint NOT NULL REFERENCES prsn_chat_threads(id) ON DELETE CASCADE,
	user_id bigint NOT NULL REFERENCES prsn_users(id) ON DELETE CASCADE,
	joined_at timestamptz NOT NULL DEFAULT now(),
	PRIMARY KEY (thread_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_prsn_chat_members_user_id
	ON prsn_chat_members(user_id);

CREATE TABLE IF NOT EXISTS prsn_chat_messages (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	thread_id bigint NOT NULL REFERENCES prsn_chat_threads(id) ON DELETE CASCADE,
	sender_id bigint NOT NULL REFERENCES prsn_users(id) ON DELETE CASCADE,
	body text NOT NULL,
	created_at timestamptz NOT NULL DEFAULT now(),
	reactions jsonb NOT NULL DEFAULT '{}'::jsonb,
	meta jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_prsn_chat_messages_thread_created
	ON prsn_chat_messages(thread_id, created_at DESC, id DESC);

ALTER TABLE prsn_chat_threads ENABLE ROW LEVEL SECURITY;
ALTER TABLE prsn_chat_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE prsn_chat_messages ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE prsn_chat_threads IS 'Parascene: chat threads (DM or hashtag channel). API + service role only.';
COMMENT ON COLUMN prsn_chat_threads.meta IS 'Parascene chat: thread-level JSON (e.g. meta.canvas.pinned_message_id for default channel canvas).';
COMMENT ON TABLE prsn_chat_members IS 'Parascene: thread membership. API + service role only.';
COMMENT ON TABLE prsn_chat_messages IS 'Parascene: chat messages. API + service role only.';

-- Paginated fetch: latest rows first; optional cursor = strictly older than (p_before_created_at, p_before_id).
CREATE OR REPLACE FUNCTION prsn_chat_messages_page(
	p_thread_id bigint,
	p_before_created_at timestamptz,
	p_before_id bigint,
	p_limit int
)
RETURNS SETOF prsn_chat_messages
LANGUAGE sql
STABLE
AS $$
	SELECT m.*
	FROM prsn_chat_messages m
	WHERE m.thread_id = p_thread_id
	AND (
		(p_before_created_at IS NULL AND p_before_id IS NULL)
		OR (m.created_at, m.id) < (p_before_created_at, p_before_id)
	)
	ORDER BY m.created_at DESC, m.id DESC
	LIMIT p_limit;
$$;

-- Chat: list threads for a user (last message preview). Run after supabase_03.sql.

CREATE OR REPLACE FUNCTION prsn_chat_threads_for_user(p_user_id bigint)
RETURNS TABLE (
	thread_id bigint,
	thread_type text,
	dm_pair_key text,
	channel_slug text,
	thread_created_at timestamptz,
	last_message_at timestamptz,
	last_message_body text,
	last_sender_id bigint
)
LANGUAGE sql
STABLE
AS $$
	SELECT
		t.id,
		t.type,
		t.dm_pair_key,
		t.channel_slug,
		t.created_at,
		lm.created_at,
		lm.body,
		lm.sender_id
	FROM prsn_chat_members m
	INNER JOIN prsn_chat_threads t ON t.id = m.thread_id
	LEFT JOIN LATERAL (
		SELECT m2.created_at, m2.body, m2.sender_id
		FROM prsn_chat_messages m2
		WHERE m2.thread_id = t.id
		ORDER BY m2.created_at DESC, m2.id DESC
		LIMIT 1
	) lm ON true
	WHERE m.user_id = p_user_id
	ORDER BY COALESCE(lm.created_at, t.created_at) DESC;
$$;

-- Reactions live on the message row: reactions jsonb = { "thumbsUp": [user_id, ...], ... }.
-- If you previously created prsn_chat_message_reactions, migrate then: DROP TABLE IF EXISTS prsn_chat_message_reactions;
ALTER TABLE prsn_chat_messages ADD COLUMN IF NOT EXISTS reactions jsonb NOT NULL DEFAULT '{}'::jsonb;
COMMENT ON COLUMN prsn_chat_messages.reactions IS 'Parascene chat: emoji_key -> user id list (API validates keys against REACTION_ORDER).';

ALTER TABLE prsn_chat_threads
	ADD COLUMN IF NOT EXISTS meta jsonb NOT NULL DEFAULT '{}'::jsonb;

-- ---------------------------------------------------------------------------
-- Realtime Broadcast (invalidation bus): policies on realtime.messages
-- ---------------------------------------------------------------------------
-- Authenticated users may receive (subscribe to) broadcast only. INSERT/send is not granted here:
-- the service_role key bypasses RLS, so API/workers publish via getSupabaseServiceClient() only.
-- Chat authorization stays in the HTTP API; invalidation hints may be observable (accepted tradeoff).
-- Use private channels in the client (`private: true`) and disable Realtime "Allow public access"
-- so only authenticated JWTs can attach (anon has no policies here).
-- Upgrade: if you had INSERT for authenticated, run:
--   DROP POLICY IF EXISTS "prsn_realtime_broadcast_insert" ON realtime.messages;

CREATE POLICY "prsn_realtime_broadcast_select"
	ON realtime.messages
	FOR SELECT
	TO authenticated
	USING (realtime.messages.extension = 'broadcast');

COMMENT ON POLICY "prsn_realtime_broadcast_select" ON realtime.messages IS 'Parascene: authenticated may receive broadcast; publish via service_role only.';
