-- OAuth-style integration ("Log in with Parascene"). Run after core user tables exist.

CREATE TABLE IF NOT EXISTS prsn_oauth_clients (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	client_id text NOT NULL UNIQUE,
	owner_user_id bigint NOT NULL REFERENCES prsn_users(id) ON DELETE CASCADE,
	name text NOT NULL,
	redirect_uris jsonb NOT NULL DEFAULT '[]'::jsonb,
	created_at timestamptz NOT NULL DEFAULT now(),
	meta jsonb
);

CREATE INDEX IF NOT EXISTS idx_prsn_oauth_clients_owner ON prsn_oauth_clients(owner_user_id);

COMMENT ON TABLE prsn_oauth_clients IS 'Parascene: registered OAuth integration apps (developer-owned).';

CREATE TABLE IF NOT EXISTS prsn_oauth_authorization_codes (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	code_hash text NOT NULL UNIQUE,
	user_id bigint NOT NULL REFERENCES prsn_users(id) ON DELETE CASCADE,
	oauth_client_id bigint NOT NULL REFERENCES prsn_oauth_clients(id) ON DELETE CASCADE,
	redirect_uri text NOT NULL,
	code_challenge text NOT NULL,
	expires_at timestamptz NOT NULL,
	consumed_at timestamptz,
	created_at timestamptz NOT NULL DEFAULT now(),
	meta jsonb
);

CREATE INDEX IF NOT EXISTS idx_prsn_oauth_codes_expires ON prsn_oauth_authorization_codes(expires_at);

COMMENT ON TABLE prsn_oauth_authorization_codes IS 'Parascene: short-lived PKCE-bound OAuth authorization codes.';

CREATE TABLE IF NOT EXISTS prsn_oauth_grants (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id bigint NOT NULL REFERENCES prsn_users(id) ON DELETE CASCADE,
	oauth_client_id bigint NOT NULL REFERENCES prsn_oauth_clients(id) ON DELETE CASCADE,
	refresh_token_hash text UNIQUE,
	scopes text NOT NULL DEFAULT 'openid profile',
	created_at timestamptz NOT NULL DEFAULT now(),
	revoked_at timestamptz,
	last_used_at timestamptz,
	meta jsonb
);

CREATE INDEX IF NOT EXISTS idx_prsn_oauth_grants_user ON prsn_oauth_grants(user_id);
CREATE INDEX IF NOT EXISTS idx_prsn_oauth_grants_client ON prsn_oauth_grants(oauth_client_id);

COMMENT ON TABLE prsn_oauth_grants IS 'Parascene: refresh tokens / connected-app grants for integrations.';

COMMENT ON COLUMN prsn_oauth_clients.meta IS 'Parascene: optional extension JSON for the integration app record.';
COMMENT ON COLUMN prsn_oauth_authorization_codes.meta IS 'Parascene: optional extension JSON for the authorization code row.';
COMMENT ON COLUMN prsn_oauth_grants.meta IS 'Parascene: optional extension JSON for the grant row.';

ALTER TABLE prsn_oauth_clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE prsn_oauth_authorization_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE prsn_oauth_grants ENABLE ROW LEVEL SECURITY;
