-- Audio clip library: reusable audio for audio-to-video and prompt library.
-- Run after supabase_01.sql (requires prsn_users, prsn_created_images).

CREATE TABLE IF NOT EXISTS prsn_audio_clips (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	title text NOT NULL,
	description text,
	storage_key text NOT NULL,
	content_type text NOT NULL,
	byte_size bigint NOT NULL,
	duration_sec real,
	source_type text NOT NULL CHECK (source_type IN ('video_extract', 'recorded', 'upload')),
	source_created_image_id bigint REFERENCES prsn_created_images(id) ON DELETE SET NULL,
	meta jsonb NOT NULL DEFAULT '{}'::jsonb,
	usage_count bigint NOT NULL DEFAULT 0,
	last_used_at timestamptz,
	deleted_at timestamptz,
	is_active boolean NOT NULL DEFAULT true,
	created_at timestamptz NOT NULL DEFAULT now(),
	updated_at timestamptz NOT NULL DEFAULT now(),
	CONSTRAINT prsn_audio_clips_storage_key_unique UNIQUE (storage_key)
);

-- Owner ids in meta.owners: { "creator": <user_id>, "source": <user_id>? }
CREATE INDEX IF NOT EXISTS idx_prsn_audio_clips_owners_creator
	ON prsn_audio_clips (((meta->'owners'->>'creator')::bigint))
	WHERE deleted_at IS NULL AND is_active = true;

CREATE INDEX IF NOT EXISTS idx_prsn_audio_clips_owners_source
	ON prsn_audio_clips (((meta->'owners'->>'source')::bigint))
	WHERE deleted_at IS NULL AND is_active = true AND (meta->'owners'->>'source') IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_prsn_audio_clips_last_used_at_list
	ON prsn_audio_clips (last_used_at DESC NULLS LAST, id DESC)
	WHERE deleted_at IS NULL AND is_active = true;

CREATE INDEX IF NOT EXISTS idx_prsn_audio_clips_usage_count_list
	ON prsn_audio_clips (usage_count DESC, id DESC)
	WHERE deleted_at IS NULL AND is_active = true;

CREATE INDEX IF NOT EXISTS idx_prsn_audio_clips_source_created_image_id
	ON prsn_audio_clips (source_created_image_id)
	WHERE source_created_image_id IS NOT NULL;

ALTER TABLE prsn_audio_clips ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE prsn_audio_clips IS 'Parascene: reusable audio clips (storage pointer + meta.owners for auth/UI). RLS enabled without policies - only service role can access. All access controlled via API layer.';

CREATE TABLE IF NOT EXISTS prsn_audio_clip_usages (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	audio_clip_id bigint NOT NULL REFERENCES prsn_audio_clips(id) ON DELETE CASCADE,
	created_image_id bigint NOT NULL REFERENCES prsn_created_images(id) ON DELETE CASCADE,
	used_at timestamptz NOT NULL DEFAULT now(),
	meta jsonb NOT NULL DEFAULT '{}'::jsonb,
	CONSTRAINT prsn_audio_clip_usages_created_image_id_unique UNIQUE (created_image_id)
);

CREATE INDEX IF NOT EXISTS idx_prsn_audio_clip_usages_clip_used_at
	ON prsn_audio_clip_usages (audio_clip_id, used_at DESC);

ALTER TABLE prsn_audio_clip_usages ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE prsn_audio_clip_usages IS 'Parascene: links an audio clip to an A2V output creation. Hub "Used in" grid; creation detail uses meta.audio_clip snapshot on the creation row.';
