-- Prompt injection tags: slug + tag_type maps to injection_text (sigil comes from tag_type at prompt/UI time, not stored in tag).
-- Run after supabase_01.sql (standalone additive migration).

CREATE TABLE IF NOT EXISTS prsn_prompt_injections (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	tag text NOT NULL,
	tag_type text NOT NULL,
	injection_text text NOT NULL,
	title text,
	description text,
	meta jsonb,
	owner_user_id bigint REFERENCES prsn_users(id) ON DELETE CASCADE,
	visibility text NOT NULL DEFAULT 'private' CHECK (visibility IN ('private', 'public', 'unlisted')),
	priority integer NOT NULL DEFAULT 0,
	replaces_global boolean NOT NULL DEFAULT false,
	deleted_at timestamptz,
	published_at timestamptz,
	moderation_status text CHECK (moderation_status IS NULL OR moderation_status IN ('pending', 'approved', 'rejected')),
	reviewed_at timestamptz,
	forked_from_id bigint REFERENCES prsn_prompt_injections(id) ON DELETE SET NULL,
	usage_count bigint NOT NULL DEFAULT 0,
	last_used_at timestamptz,
	locale text,
	is_active boolean NOT NULL DEFAULT true,
	created_at timestamptz NOT NULL DEFAULT now(),
	updated_at timestamptz NOT NULL DEFAULT now()
);

-- One global/system row per (tag, tag_type); one row per (user, tag, tag_type) for user-owned rows. Same slug may repeat across tag_type (e.g. persona vs style). Soft-deleted rows excluded.
DROP INDEX IF EXISTS idx_prsn_prompt_injections_tag_lower;
DROP INDEX IF EXISTS idx_prsn_prompt_injections_tag_global_unique;
DROP INDEX IF EXISTS idx_prsn_prompt_injections_tag_user_unique;

CREATE UNIQUE INDEX IF NOT EXISTS idx_prsn_prompt_injections_tag_global_unique
	ON prsn_prompt_injections (lower(tag), tag_type)
	WHERE owner_user_id IS NULL AND deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_prsn_prompt_injections_tag_user_unique
	ON prsn_prompt_injections (owner_user_id, lower(tag), tag_type)
	WHERE owner_user_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_prsn_prompt_injections_tag_type_active
	ON prsn_prompt_injections (tag_type)
	WHERE is_active = true;

CREATE INDEX IF NOT EXISTS idx_prsn_prompt_injections_owner
	ON prsn_prompt_injections (owner_user_id)
	WHERE owner_user_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_prsn_prompt_injections_public_listing
	ON prsn_prompt_injections (visibility, tag_type, lower(tag))
	WHERE visibility = 'public' AND deleted_at IS NULL AND is_active = true;

ALTER TABLE prsn_prompt_injections ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE prsn_prompt_injections IS 'Parascene: prompt injection catalog (slug + tag_type → injection_text; styles, personas, etc.). Global and per-user rows, visibility, moderation. RLS enabled without policies - only service role can access. All access controlled via API layer.';
